import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { Layout } from "../layouts/default";

const Home: NextPage = () => {
  return (
    <Layout>
      <Head>
        <title>Project Pals</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex w-full flex-col items-center gap-12 p-8">
        <h1 className="text-5xl font-extrabold tracking-tight text-gray-800 sm:text-[5rem]">
          Project<span className="text-purple-600 text-opacity-70">Pals</span>
        </h1>
        <div className="flex flex-col justify-center gap-5 text-3xl font-bold text-gray-800 md:flex-row">
          <Link
            href="/projects"
            className="flex items-center gap-8 rounded-2xl bg-purple-600 bg-opacity-[.15] p-8 transition-colors hover:bg-opacity-25 md:w-5/12 md:flex-col lg:flex-row"
          >
            <Image
              src="idea-icon.svg"
              alt="project idea icon"
              width={80}
              height={80}
            />
            I&apos;m looking for a project to join
          </Link>
          <Link
            href="/pals"
            className="flex items-center gap-8 rounded-2xl bg-purple-600 bg-opacity-[.15] p-8 transition-colors hover:bg-opacity-25 md:w-5/12 md:flex-col lg:flex-row"
          >
            <Image
              src="networking-icon.svg"
              alt="people network icon"
              width={80}
              height={80}
            />
            I&apos;m looking for somebody to join my project
          </Link>
        </div>
      </div>
    </Layout>
  );
};

export default Home;
