import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { Layout } from "../layouts/default";

const Home: NextPage = () => {
  return (
    <Layout>
      <Head>
        <title>Project Pals</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gray-50">
        <div className="flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-gray-800 sm:text-[5rem]">
            Project<span className="text-purple-600 text-opacity-70">Pals</span>
          </h1>
          <div className="flex justify-center gap-x-5 text-3xl font-bold text-gray-800">
            <Link
              href="/projects"
              className="flex w-5/12 items-center gap-8 rounded-2xl bg-purple-600 bg-opacity-[.15] p-8 transition-colors hover:bg-opacity-25"
            >
              <Image
                src="idea-icon.svg"
                alt="project idea icon"
                width={80}
                height={80}
              />
              I&apos;m looking for a project to join
            </Link>
            <Link
              href="/pals"
              className="flex w-5/12 items-center gap-8 rounded-2xl bg-purple-600 bg-opacity-[.15] p-8 transition-colors hover:bg-opacity-25"
            >
              <Image
                src="networking-icon.svg"
                alt="people network icon"
                width={80}
                height={80}
              />
              I&apos;m looking for somebody to join my project
            </Link>
          </div>
        </div>
      </main>
    </Layout>
  );
};

export default Home;
