import { type NextPage } from "next";
import Head from "next/head";

import { UserList } from "../components/userList";
import { Layout } from "../layouts/default";

const Profiles: NextPage = () => {
  return (
    <Layout>
      <Head>
        <title>Project Pals</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col items-center justify-center gap-12 px-4 py-16 ">
        <h1 className="text-5xl font-extrabold tracking-tight text-gray-800 sm:text-[5rem]">
          Pals
        </h1>
        <div className="flex flex-col items-center gap-2">
          <UserList />
        </div>
      </div>
    </Layout>
  );
};

export default Profiles;
